/**
 * NEXUS ROLLING LOTO ISOLATION POINTS
 * Each point is independently identified, control-locked, and QEW verified de-energized.
 * Changes invalidate prior displayed-boundary acceptance.
 */
(function(){
"use strict";
function api(){return window.NEXUSOneLineLayers;}function uid(p){return p+"-"+Date.now()+"-"+Math.random().toString(36).slice(2,7);}function now(){return new Date().toISOString();}
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function equipment(){return Array.from(document.querySelectorAll(".nexus-one-line .node .id")).map(x=>String(x.textContent||"").trim()).filter(Boolean);}
function active(d){return d.lotos.filter(x=>x&&x.status!=="closed");}
function points(l){if(Array.isArray(l.isolationPoints))return l.isolationPoints;return l.isolationPoint?[{id:uid("legacy-isolation"),equipmentId:l.isolationPoint,status:"identified",locked:false,verifiedDeenergized:false}]:[];}
function invalidate(l,actor,t,reason){l.boundaryAcceptance={accepted:false,invalidatedAt:t,invalidatedBy:actor,invalidationReason:reason};}
function install(){
 const modal=document.createElement("div");modal.className="nx-loto-start-modal";document.body.appendChild(modal);
 function close(){modal.classList.remove("is-open");modal.innerHTML="";}
 function open(){const d=api().loadLoto(),ls=active(d);modal.innerHTML='<div class="nx-loto-dialog nx-isolation-dialog"><header><div><span>ROLLING ISOLATION</span><h2>Isolation Points</h2></div><button data-cancel>×</button></header>'+(ls.length?'<label>Recorded LOTO<select data-loto>'+ls.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.lotoNumber||x.id)+'</option>').join("")+'</select></label><div data-points></div>':'<div class="nx-lock-message">No active Recorded LOTO.</div>')+'</div>';modal.classList.add("is-open");const s=modal.querySelector("[data-loto]");if(s){s.addEventListener("change",render);render();}}
 function render(){const d=api().loadLoto(),l=d.lotos.find(x=>x.id===modal.querySelector("[data-loto]")?.value),box=modal.querySelector("[data-points]");if(!l||!box)return;l.isolationPoints=points(l);box.innerHTML='<div class="nx-boundary-status"><b>Displayed Boundary: '+(l.boundaryAcceptance&&l.boundaryAcceptance.accepted?"ACCEPTED":"REVIEW REQUIRED")+'</b><span>Any isolation-point change invalidates previous boundary acceptance. NEXUS is a visual aid; always verify field conditions.</span></div>'+l.isolationPoints.map(p=>'<article class="nx-isolation-point"><strong>'+esc(p.equipmentId)+'</strong><div><span>'+(p.identifiedAt?"✓":"○")+' Identified</span><span>'+(p.locked?"✓":"○")+' Control Lock</span><span>'+(p.verifiedDeenergized?"✓":"○")+' QEW Verified De-energized</span></div><small>Control lock: '+esc(p.controlLockId||"Not recorded")+'</small><div class="nx-isolation-actions">'+(!p.locked?'<button data-lock="'+esc(p.id)+'">Record Lock</button>':'')+(!p.verifiedDeenergized?'<button data-verify="'+esc(p.id)+'">QEW Verify</button>':'')+'</div></article>').join("")+'<button class="nx-add-isolation" data-add>+ Add Isolation Point</button><button data-accept-boundary>Accept Displayed Boundary</button>';}
 function saveEvent(d,l,p,type,actor,payload){d.events.push({id:uid("event"),type,timestamp:now(),actor,layer:"loto",recordId:p&&p.id,lotoId:l.id,lotoNumber:l.lotoNumber,equipmentId:p&&p.equipmentId,payload:payload||{}});}
 modal.addEventListener("click",e=>{if(e.target.closest("[data-cancel]"))return close();const d=api().loadLoto(),l=d.lotos.find(x=>x.id===modal.querySelector("[data-loto]")?.value);if(!l)return;l.isolationPoints=points(l);
  if(e.target.closest("[data-add]")){const eq=prompt("Isolation point equipment ID:",equipment()[0]||"");if(!eq)return;const actor=prompt("Identified by:","");if(!actor)return;const t=now(),p={id:uid("isolation"),equipmentId:eq,status:"identified",identifiedAt:t,identifiedBy:actor,locked:false,verifiedDeenergized:false};l.isolationPoints.push(p);invalidate(l,actor,t,"Isolation point added");saveEvent(d,l,p,"ISOLATION_POINT_IDENTIFIED",actor);api().saveLoto(d);render();return;}
  const lock=e.target.closest("[data-lock]");if(lock){const p=l.isolationPoints.find(x=>x.id===lock.dataset.lock);if(!p)return;const lockId=prompt("Control lock ID / number:","");if(!lockId)return;const actor=prompt("Lock applied by:","");if(!actor)return;const t=now();p.locked=true;p.status="locked";p.controlLockId=lockId;p.lockedAt=t;p.lockedBy=actor;invalidate(l,actor,t,"Isolation lock state changed");saveEvent(d,l,p,"ISOLATION_POINT_LOCKED",actor,{controlLockId:lockId});api().saveLoto(d);render();return;}
  const verify=e.target.closest("[data-verify]");if(verify){const p=l.isolationPoints.find(x=>x.id===verify.dataset.verify);if(!p||!p.locked)return alert("Record the control lock before QEW verification.");const qew=prompt("QEW name:","");if(!qew)return;const t=now();p.verifiedDeenergized=true;p.status="qew_verified_deenergized";p.qewVerifiedAt=t;p.qewVerifiedBy=qew;invalidate(l,qew,t,"QEW verification changed");saveEvent(d,l,p,"ISOLATION_POINT_QEW_VERIFIED_DEENERGIZED",qew);api().saveLoto(d);render();return;}
  if(e.target.closest("[data-accept-boundary]")){if(l.isolationPoints.some(p=>!p.locked||!p.verifiedDeenergized))return alert("Every recorded isolation point must be control-locked and QEW verified before accepting the displayed boundary.");const actor=prompt("LOTO Coordinator accepting displayed boundary:","");if(!actor)return;const t=now();l.boundaryAcceptance={accepted:true,acceptedAt:t,acceptedBy:actor};saveEvent(d,l,null,"LOTO_DISPLAYED_BOUNDARY_ACCEPTED",actor,{isolationPointIds:l.isolationPoints.map(p=>p.id)});api().saveLoto(d);render();}
 });
 window.addEventListener("nexus:loto-isolation-request",open);window.addEventListener("keydown",e=>{if(e.key==="Escape"&&modal.classList.contains("is-open"))close();});
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install);else install();
})();