/**
 * NEXUS LOTO RELEASE / RESTORATION WORKFLOW
 * Stage 9: staged lifecycle. No stage establishes electrical safety.
 */
(function(){
"use strict";
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function api(){return window.NEXUSOneLineLayers;}
function uid(p){return p+"-"+Date.now()+"-"+Math.random().toString(36).slice(2,7);}
function now(){return new Date().toISOString();}
function activeLocks(d,id){return d.personalLocks.filter(x=>x&&String(x.status||"").toLowerCase()!=="removed"&&String(x.lotoId)===String(id));}
const stages=["active","work_complete","personal_protection_clear","released","restoration_authorized","restored","closed"];
const names={active:"Work Active",work_complete:"Work Complete",personal_protection_clear:"Personal Protection Clear",released:"Recorded LOTO Released",restoration_authorized:"Restoration Authorized",restored:"Restored",closed:"Closed"};
const events={work_complete:"LOTO_WORK_COMPLETE",personal_protection_clear:"LOTO_PERSONAL_PROTECTION_CLEAR",released:"LOTO_RELEASED",restoration_authorized:"LOTO_RESTORATION_AUTHORIZED",restored:"LOTO_RESTORED",closed:"LOTO_CLOSED"};
function current(l){return stages.includes(l.status)?l.status:"active";}
function next(l){return stages[stages.indexOf(current(l))+1]||null;}
function install(){
 const modal=document.createElement("div");modal.className="nx-loto-start-modal";modal.setAttribute("aria-hidden","true");document.body.appendChild(modal);
 function close(){modal.classList.remove("is-open");modal.setAttribute("aria-hidden","true");modal.innerHTML="";}
 function show(html){modal.innerHTML=html;modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");}
 function removePerson(){if(!api()||!api().can("loto","participate"))return;const d=api().loadLoto(),locks=d.personalLocks.filter(x=>x&&String(x.status||"").toLowerCase()!=="removed");show('<div class="nx-loto-dialog"><header><div><span>PERSONAL PROTECTION</span><h2>Remove Person / Lock</h2></div><button type="button" data-cancel>×</button></header>'+(locks.length?'<form data-release-form><label>Active Personal Lock<select name="lockRecordId" required>'+locks.map(l=>'<option value="'+esc(l.id)+'">'+esc(l.personName||l.personId)+' — '+esc(l.lockId||l.lockNumber)+' — '+esc(l.equipmentId)+'</option>').join("")+'</select></label><label>Removed By<input name="removedBy" required></label><label class="nx-loto-confirm"><input type="checkbox" required><span>The physical personal lock has been removed by its authorized owner. Exceptional removal requires the separate Coordinator removal workflow.</span></label><footer><button type="button" data-cancel>Cancel</button><button type="submit" class="primary">Record Lock Removal</button></footer></form>':'<div class="nx-lock-message">There are no active personal locks to remove.</div>')+'</div>');}
 function exceptionalRemoval(){if(!api()||!api().can("loto","manage"))return;const d=api().loadLoto(),locks=d.personalLocks.filter(x=>x&&String(x.status||"").toLowerCase()!=="removed");show('<div class="nx-loto-dialog"><header><div><span>EXCEPTIONAL REMOVAL</span><h2>Personal Lock Removal Record</h2></div><button type="button" data-cancel>×</button></header>'+(locks.length?'<form data-exception-form><label>Active Personal Lock<select name="lockRecordId" required>'+locks.map(l=>'<option value="'+esc(l.id)+'">'+esc(l.personName||l.personId)+' — '+esc(l.lockId||l.lockNumber)+' — '+esc(l.equipmentId)+'</option>').join("")+'</select></label><label>LOTO Coordinator<input name="coordinator" required></label><label>Reason for Exceptional Removal<textarea name="reason" rows="4" required></textarea></label><label class="nx-loto-confirm"><input type="checkbox" required><span>This is an exceptional removal record. The reason must be documented before the physical lock is recorded as removed.</span></label><footer><button type="button" data-cancel>Cancel</button><button type="submit" class="primary">Record Exceptional Removal</button></footer></form>':'<div class="nx-lock-message">There are no active personal locks.</div>')+'</div>');}
 function progress(){if(!api()||!api().can("loto","manage"))return;const d=api().loadLoto(),lotos=d.lotos.filter(l=>current(l)!=="closed");show('<div class="nx-loto-dialog nx-lifecycle-dialog"><header><div><span>RECORDED LOTO</span><h2>Release / Restore</h2></div><button type="button" data-cancel>×</button></header>'+(lotos.length?'<form data-progress-form><label>Recorded LOTO<select name="lotoId" required>'+lotos.map(l=>'<option value="'+esc(l.id)+'">'+esc(l.lotoNumber||l.id)+' — '+esc(names[current(l)])+'</option>').join("")+'</select></label><div class="nx-lifecycle-state"></div><label>LOTO Coordinator<input name="actor" required placeholder="Coordinator name"></label><label>Record Note<textarea name="note" rows="3" required placeholder="Record the field condition supporting this transition"></textarea></label><label class="nx-loto-confirm"><input type="checkbox" required><span>This records an observed/authorized field step only. NEXUS is a visual and recordkeeping aid and does not guarantee a de-energized or safe electrical condition. Always verify in the field.</span></label><footer><button type="button" data-cancel>Cancel</button><button type="submit" class="primary">Record Next Stage</button></footer></form>':'<div class="nx-lock-message">There are no Recorded LOTOs awaiting completion.</div>')+'</div>');const s=modal.querySelector('[name="lotoId"]');if(s){s.addEventListener("change",renderState);renderState();}}
 function renderState(){const id=modal.querySelector('[name="lotoId"]')?.value,box=modal.querySelector(".nx-lifecycle-state");if(!id||!box)return;const d=api().loadLoto(),l=d.lotos.find(x=>x.id===id),n=next(l),locks=activeLocks(d,id);let blocked="";if(n==="personal_protection_clear"&&locks.length)blocked='<div class="nx-stage-blocked"><b>BLOCKED</b> '+locks.length+' personal lock'+(locks.length===1?" remains":"s remain")+'.</div>';box.innerHTML='<div class="nx-stage-current"><span>Current</span><b>'+esc(names[current(l)])+'</b></div><div class="nx-stage-arrow">→</div><div class="nx-stage-next"><span>Next</span><b>'+esc(names[n]||"Complete")+'</b></div>'+blocked;}
 modal.addEventListener("click",e=>{if(e.target===modal||e.target.closest("[data-cancel]"))close();});
 modal.addEventListener("submit",e=>{e.preventDefault();const form=e.target,fd=new FormData(form),d=api().loadLoto();
  if(form.hasAttribute("data-exception-form")){const lock=d.personalLocks.find(l=>l.id===fd.get("lockRecordId")&&String(l.status||"").toLowerCase()!=="removed");if(!lock)return;const t=now(),actor=String(fd.get("coordinator")||"").trim(),reason=String(fd.get("reason")||"").trim();if(!actor||!reason)return;lock.status="removed";lock.removedAt=t;lock.removedBy=actor;lock.physicalStateRecorded="exceptional_removal_recorded";lock.removalType="exceptional";lock.exceptionalRemovalReason=reason;d.events.push({id:uid("event"),type:"PERSONAL_LOCK_EXCEPTION_REMOVED",timestamp:t,actor,personId:lock.personId,personName:lock.personName,layer:"loto",recordId:lock.id,lotoId:lock.lotoId,lotoNumber:lock.lotoNumber,equipmentId:lock.equipmentId,lockId:lock.lockId,payload:{physicalState:"exceptional_removal_recorded",reason}});api().saveLoto(d);close();return;}
  if(form.hasAttribute("data-release-form")){const lock=d.personalLocks.find(l=>l.id===fd.get("lockRecordId")&&String(l.status||"").toLowerCase()!=="removed");if(!lock)return;const t=now(),actor=String(fd.get("removedBy")||"").trim();lock.status="removed";lock.removedAt=t;lock.removedBy=actor;lock.physicalStateRecorded="removed";d.events.push({id:uid("event"),type:"PERSONAL_LOCK_REMOVED",timestamp:t,actor,personId:lock.personId,personName:lock.personName,layer:"loto",recordId:lock.id,lotoId:lock.lotoId,lotoNumber:lock.lotoNumber,equipmentId:lock.equipmentId,lockId:lock.lockId,payload:{physicalState:"removed"}});api().saveLoto(d);close();return;}
  const l=d.lotos.find(x=>x.id===fd.get("lotoId"));if(!l)return;const n=next(l);if(!n)return;if(n==="personal_protection_clear"&&activeLocks(d,l.id).length){renderState();return;}if(n==="personal_protection_clear"&&Array.isArray(l.groupBoxes)){const uncleared=l.groupBoxes.filter(b=>b&&b.status!=="cleared");if(uncleared.length){alert("Record each group box as clear before Personal Protection Clear. Active group boxes: "+uncleared.map(b=>b.groupBoxId).join(", "));return;}}const t=now(),actor=String(fd.get("actor")||"").trim(),note=String(fd.get("note")||"").trim();if(l.lotoCoordinator&&actor!==String(l.lotoCoordinator).trim()){alert("This Recorded LOTO is currently assigned to "+l.lotoCoordinator+". Use Coordinator Handoff before another Coordinator records lifecycle actions.");return;}l.status=n;l.updatedAt=t;l.updatedBy=actor;l.lifecycle=l.lifecycle||[];l.lifecycle.push({stage:n,timestamp:t,actor,note});if(n==="closed"){l.closedAt=t;l.closedBy=actor;}d.events.push({id:uid("event"),type:events[n],timestamp:t,actor,layer:"loto",recordId:l.id,lotoId:l.id,lotoNumber:l.lotoNumber,equipmentId:l.equipmentId,payload:{status:n,note}});api().saveLoto(d);close();
 });
 window.addEventListener("nexus:loto-remove-person-request",removePerson);window.addEventListener("nexus:loto-exception-remove-request",exceptionalRemoval);window.addEventListener("nexus:loto-progress-request",progress);window.addEventListener("keydown",e=>{if(e.key==="Escape"&&modal.classList.contains("is-open"))close();});
}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install);else install();
})();