/**
 * NEXUS LOTO VISUAL STATE
 * At-a-glance operational badges over the SME-built One-Line.
 */
(function(){"use strict";
function api(){return window.NEXUSOneLineLayers;}
function node(id){return Array.from(document.querySelectorAll(".nexus-one-line .node")).find(n=>{const x=n.querySelector(".id");return x&&String(x.textContent||"").trim()===String(id);});}
function clear(){document.querySelectorAll(".nx-loto-visual-badges").forEach(x=>x.remove());document.querySelectorAll(".node.nx-loto-protected,.node.nx-loto-point,.node.nx-loto-people").forEach(n=>n.classList.remove("nx-loto-protected","nx-loto-point","nx-loto-people"));}
function add(n,label,cls,title,detail){let h=n.querySelector(".nx-loto-visual-badges");if(!h){h=document.createElement("div");h.className="nx-loto-visual-badges";n.appendChild(h);}const b=document.createElement("button");b.type="button";b.className="nx-loto-visual-badge "+cls;b.textContent=label;b.title=title||label;b.addEventListener("click",e=>{e.stopPropagation();n.dispatchEvent(new MouseEvent("click",{bubbles:true}));window.dispatchEvent(new CustomEvent("nexus:loto-object-open",{detail:detail||{equipmentId:String((n.querySelector(".id")||{}).textContent||"").trim(),type:cls}}));});h.appendChild(b);}
function render(){clear();if(document.body.dataset.nexusLayer!=="loto"||!api())return;const d=api().loadLoto(),active=d.lotos.filter(l=>l&&l.status!=="closed"),locks=d.personalLocks.filter(l=>l&&l.status!=="removed");const coverage=new Map();active.forEach(l=>{(l.boundaryAcceptance&&l.boundaryAcceptance.accepted?l.boundaryAcceptance.downstreamEquipmentIds||[]:[]).forEach(id=>{const a=coverage.get(String(id))||[];a.push(l);coverage.set(String(id),a);});(l.boundaryAcceptance&&l.boundaryAcceptance.accepted?l.boundaryAcceptance.downstreamEquipmentIds||[]:[]).forEach(id=>{const n=node(id);if(n){n.classList.add("nx-loto-protected");add(n,"PROTECTED","protected","Inside accepted displayed LOTO boundary",{type:"protected-equipment",equipmentId:String(id),lotoId:l.id});}});(l.isolationPoints||[]).forEach(p=>{const n=node(p.equipmentId);if(n){n.classList.add("nx-loto-point");add(n,"ISOLATION","isolation","Recorded LOTO isolation point"+(p.controlLockId?" · Control lock "+p.controlLockId:""),{type:"isolation-point",equipmentId:String(p.equipmentId),lotoId:l.id,isolationPointId:p.id});}});});coverage.forEach((ls,id)=>{if(ls.length<2)return;const n=node(id);if(n)add(n,ls.length+" ACTIVE LOTOs","overlap","This equipment is inside multiple active Recorded LOTO boundaries",{type:"loto-overlap",equipmentId:id,lotoIds:ls.map(x=>x.id)});});const by=new Map();locks.forEach(l=>{if(!l.equipmentId)return;const a=by.get(String(l.equipmentId))||[];a.push(l);by.set(String(l.equipmentId),a);});by.forEach((ls,id)=>{const n=node(id);if(!n)return;n.classList.add("nx-loto-people");const people=new Set(ls.map(x=>x.personId||x.personName));add(n,people.size+" PERSON"+(people.size===1?"":"S"),"people",ls.length+" active personal lock"+(ls.length===1?"":"s"),{type:"people-locks",equipmentId:String(id),lockIds:ls.map(x=>x.id)});});}
window.addEventListener("nexus:loto-change",render);window.addEventListener("nexus:layerchange",render);window.addEventListener("nexus:loto-topology-view",render);setTimeout(render,0);
})();