/**
 * NEXUS LOTO GROUP BOX RECORDS
 * Records physical group boxes and custody of isolation-device control-lock keys.
 */
(function(){"use strict";
function api(){return window.NEXUSOneLineLayers;}function uid(p){return p+"-"+Date.now()+"-"+Math.random().toString(36).slice(2,7);}function now(){return new Date().toISOString();}
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function boxes(l){if(!Array.isArray(l.groupBoxes))l.groupBoxes=[];return l.groupBoxes;}
function install(){const m=document.createElement("div");m.className="nx-loto-start-modal";document.body.appendChild(m);function close(){m.classList.remove("is-open");m.innerHTML="";}
function open(){const d=api().loadLoto(),ls=d.lotos.filter(x=>x&&x.status!=="closed");m.innerHTML='<div class="nx-loto-dialog"><header><div><span>GROUP PROTECTION</span><h2>Group Boxes</h2></div><button data-cancel>×</button></header>'+(ls.length?'<label>Recorded LOTO<select data-loto>'+ls.map(l=>'<option value="'+esc(l.id)+'">'+esc(l.lotoNumber||l.id)+'</option>').join("")+'</select></label><div data-boxes></div>':'<div class="nx-lock-message">No active Recorded LOTO.</div>')+'</div>';m.classList.add("is-open");const s=m.querySelector("[data-loto]");if(s){s.addEventListener("change",render);render();}}
function render(){const d=api().loadLoto(),l=d.lotos.find(x=>x.id===m.querySelector("[data-loto]")?.value),host=m.querySelector("[data-boxes]");if(!l||!host)return;const bs=boxes(l);host.innerHTML=bs.map(b=>{const personal=d.personalLocks.filter(x=>x&&x.status!=="removed"&&x.lotoId===l.id&&x.protectionMethod==="group_box"&&x.groupBoxId===b.groupBoxId);return '<article class="nx-isolation-point"><strong>'+esc(b.groupBoxId)+'</strong><small>Recorded by '+esc(b.createdBy)+' · '+esc(new Date(b.createdAt).toLocaleString())+'</small><div><span>'+b.controlLockIds.length+' control-lock key'+(b.controlLockIds.length===1?"":"s")+' recorded in box</span><span>'+personal.length+' active personal lock'+(personal.length===1?"":"s")+' on box</span></div><small>Control locks: '+esc(b.controlLockIds.join(", ")||"None")+'</small></article>';}).join("")+'<button data-add-box>+ Add Group Box</button>';}
m.addEventListener("click",e=>{if(e.target.closest("[data-cancel]"))return close();if(!e.target.closest("[data-add-box]"))return;const d=api().loadLoto(),l=d.lotos.find(x=>x.id===m.querySelector("[data-loto]")?.value);if(!l)return;const id=prompt("Group Box ID / number:","");if(!id)return;if(boxes(l).some(b=>b.groupBoxId===id))return alert("That group box is already recorded on this LOTO.");const available=(l.isolationPoints||[]).filter(p=>p.locked&&p.controlLockId).map(p=>p.controlLockId);if(!available.length)return alert("Record isolation-point control locks before creating the group box record.");const selected=prompt("Control lock IDs whose keys are placed in this group box (comma separated):",available.join(", "));if(!selected)return;const ids=selected.split(",").map(x=>x.trim()).filter(Boolean);const invalid=ids.filter(x=>!available.includes(x));if(invalid.length)return alert("These control locks are not recorded on the LOTO isolation points: "+invalid.join(", "));const actor=prompt("LOTO Coordinator recording group box:","");if(!actor)return;const t=now(),b={id:uid("group-box"),groupBoxId:id,controlLockIds:ids,createdAt:t,createdBy:actor,status:"active"};boxes(l).push(b);d.events.push({id:uid("event"),type:"LOTO_GROUP_BOX_RECORDED",timestamp:t,actor,layer:"loto",lotoId:l.id,lotoNumber:l.lotoNumber,recordId:b.id,payload:{groupBoxId:id,controlLockIds:ids}});api().saveLoto(d);render();});
window.addEventListener("nexus:loto-group-box-request",open);window.addEventListener("keydown",e=>{if(e.key==="Escape"&&m.classList.contains("is-open"))close();});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install);else install();
})();