(function(){
"use strict";
function api(){return window.NEXUSOneLineLayers}function uid(p){return p+"-"+Date.now()+"-"+Math.random().toString(36).slice(2,7)}function now(){return new Date().toISOString()}function esc(v){return String(v||"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function active(){const a=api();if(!a)return null;const d=a.loadLoto();return d.lotos.find(l=>l&&l.status!=="closed"&&l.boundaryAcceptance&&l.boundaryAcceptance.accepted)||null}
function modal(){let m=document.querySelector(".nx-person-tap-modal");if(!m){m=document.createElement("div");m.className="nx-loto-start-modal nx-person-tap-modal";document.body.appendChild(m)}return m}
function close(){const m=modal();m.classList.remove("is-open");m.innerHTML=""}
function add(){const a=api(),l=active();if(!a||!l)return alert("Complete LOTO setup first.");const m=modal();m.innerHTML='<div class="nx-loto-dialog nx-person-tap"><header><div><span>'+esc(l.lotoNumber)+'</span><h2>Add Person</h2></div><button data-close>×</button></header><form><label>Name<input name="person" required autofocus></label><label>Lock #<input name="lock" required></label><footer><button type="button" data-close>Cancel</button><button class="primary">ADD</button></footer></form></div>';m.classList.add("is-open");m.querySelector("form").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),person=String(f.get("person")||"").trim(),lock=String(f.get("lock")||"").trim(),d=a.loadLoto();if(d.personalLocks.some(x=>x&&x.status!=="removed"&&String(x.lockId)===lock))return alert("That lock is already active.");const t=now(),pid=person.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),r={id:uid("personal-lock"),lotoId:l.id,lotoNumber:l.lotoNumber,status:"active",equipmentId:l.equipmentId,personId:pid,personName:person,lockId:lock,protectionMethod:"single",appliedAt:t,appliedBy:person,ownerLayer:"loto",physicalStateRecorded:"applied"};d.personalLocks.push(r);d.events.push({id:uid("event"),type:"PERSONAL_LOCK_APPLIED",timestamp:t,actor:person,personId:pid,personName:person,layer:"loto",recordId:r.id,lotoId:l.id,lotoNumber:l.lotoNumber,equipmentId:l.equipmentId,lockId:lock,payload:{physicalState:"applied",protectionMethod:"single"}});a.saveLoto(d);close();render()}}
function remove(){const a=api(),l=active();if(!a||!l)return;const d=a.loadLoto(),locks=d.personalLocks.filter(x=>x&&x.status!=="removed"&&x.lotoId===l.id),m=modal();m.innerHTML='<div class="nx-loto-dialog nx-person-tap"><header><div><span>'+esc(l.lotoNumber)+'</span><h2>Remove Person</h2></div><button data-close>×</button></header><div class="nx-person-pick">'+(locks.length?locks.map(x=>'<button data-remove="'+esc(x.id)+'"><b>'+esc(x.personName)+'</b><span>Lock '+esc(x.lockId)+'</span></button>').join(""):'<p>No people are currently on this LOTO.</p>')+'</div></div>';m.classList.add("is-open")}
function render(){if(document.body.dataset.nexusLayer!=="loto")return;const l=active(),b=document.querySelector(".nx-loto-guide");if(!l||!b)return;const d=api().loadLoto(),count=d.personalLocks.filter(x=>x&&x.status!=="removed"&&x.lotoId===l.id).length;b.innerHTML="<div class='nx-guide-progress'>"+[1,2,3,4,5].map((x,i)=>"<span class='"+(x<5?"done":"current")+"'>"+(x<5?"✓":"5")+"<small>"+["EQUIPMENT","INFO","POINTS","VERIFY","ACTIVE"][i]+"</small></span>").join("")+"</div><div class='nx-guide-copy'><small>"+esc(l.lotoNumber)+"</small><strong>LOTO ACTIVE</strong><span>"+count+" "+(count===1?"person":"people")+" currently protected</span></div><div class='nx-guide-actions'><button data-person='remove'>− PERSON</button><button data-person='add' class='primary'>+ PERSON</button></div>";b.classList.add("is-open")}
document.addEventListener("click",e=>{if(e.target.closest("[data-close]"))return close();const p=e.target.closest("[data-person]");if(p){p.dataset.person==="add"?add():remove();return}const r=e.target.closest("[data-remove]");if(r){const a=api(),d=a.loadLoto(),x=d.personalLocks.find(v=>v.id===r.dataset.remove&&v.status!=="removed");if(!x)return;const t=now();x.status="removed";x.removedAt=t;x.removedBy=x.personName;x.physicalStateRecorded="removed";d.events.push({id:uid("event"),type:"PERSONAL_LOCK_REMOVED",timestamp:t,actor:x.personName,personId:x.personId,personName:x.personName,layer:"loto",recordId:x.id,lotoId:x.lotoId,lotoNumber:x.lotoNumber,equipmentId:x.equipmentId,lockId:x.lockId,payload:{physicalState:"removed",note:"Removed from active LOTO quick action"}});a.saveLoto(d);close();render()}});
window.addEventListener("nexus:loto-change",render);window.addEventListener("nexus:layerchange",()=>setTimeout(render,0));setTimeout(render,100);
})();